# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f43fbeefe26babb86e39c8c89a9b0270d1348f184e78afd5a28a73230d094fc6fca517dff8f8133bd3dac1657c33ad1939deef302002580174d3f840738c03e6

test:
  secret_key_base: c2f3b296a70f2b2c42b9dee7e179d36a0cf94253a0a1c94b8a497de84c49a37f9aa7e2e17c81476cabee112aa3e368cbb2f059d9bf334b22d9da076cf90bc56b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
